image: ulbqb/fcw-gitpod:test

workspaceLocation: "./gitpod"

vscode:
  extensions:
    - rust-lang.rust-analyzer
    - Spoorthi.cosmy-wasmy
    - tamasfe.even-better-toml

tasks:
  - name: Setup

    command: |
      mkdir -p test
      cd test

    # init: |
    #   ##
    #   # clone tutorials
    #   cd ..
    #   git clone https://github.com/Finschia/tutorials.git
    #   cd gitpod

    #   ##
    #   # generate workspace.
    #   cargo generate --git https://github.com/Finschia/cw-workspace.git --branch feat/add_workspace_template --name tutorial --init -o

    # command: |
    #   ##
    #   #
      
    #   cd ../tutorials/localnet/single
    #   docker-compose up -d finschia faucet
    #   cd ../../../gitpod
