image: ulbqb/fcw-gitpod:finschia-2.0.1

checkoutLocation: "fcw"

workspaceLocation: "./fcw/gitpod"

vscode:
  extensions:
    - rust-lang.rust-analyzer
    - Spoorthi.cosmy-wasmy

tasks:
  - name: Setup

    init: |
      ##
      # generate workspace.
      cd gitpod
      cargo generate --git https://github.com/ulbqb/beaker-workspace.git --branch main --name tutorial --init -o
      cd ..

    command: |
      ##
      # cd into the gitpod dir.
      cd gitpod

      ##
      # print a welcome message.
      clear && printf '\e[3J'
      echo -e "
      This terminal has the \033[1mbeaker\033[0m binary already installed and ready to go.

      "