image: ulbqb/fcw-gitpod:finschia-2.0.1

checkoutLocation: "fcw"

workspaceLocation: "./fcw/gitpod"

vscode:
  extensions:
    - rust-lang.rust-analyzer
    - Spoorthi.cosmy-wasmy

tasks:
  - name: Setup

    init: |
      ##
      # clone tutorials
      cd ..
      git clone https://github.com/Finschia/tutorials.git
      cd gitpod

      ##
      # generate workspace.
      cargo generate --git https://github.com/Finschia/cw-workspace.git --branch main --name tutorial --init -o --branch feat/add_workspace_tempalte

    command: |
      ##
      #
      
      cd ../tutorials/localnet/single
      docker-compose up -d finschia faucet
      cd ../../../gitpod

      ##
      # print a welcome message.
      clear && printf '\e[3J'
      echo -e "
      This terminal has the \033[1mbeaker\033[0m binary already installed and ready to go.

      "
